# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.11"

env:
  global:
    - POETRY_VIRTUALENVS_CREATE=false  # Use the system's Python interpreter

  matrix:
    - TOX_ENV=django42
    - TOX_ENV=django50

# Cache pip and Poetry dependencies for faster builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

# Install Poetry and dependencies
before_install:
  - curl -sSL https://install.python-poetry.org | python3 -
  - export PATH="$HOME/.local/bin:$PATH"
  - poetry --version

install:
  - poetry install --with=dev,qa

# Run the tests
script: tox -e $TOX_ENV

# Upload coverage to Codecov
after_success:
  - codecov -e TOX_ENV
